openapi: 3.0.0
info:
  title: AI Chatbot API for Todo Management
  description: API for natural language interaction with todo management system
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI chatbot
      description: Process natural language commands for todo management
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Better Auth token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message/command
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: string
                  description: Optional conversation ID for maintaining context
                  format: uuid
              required:
                - message
      responses:
        '200':
          description: Successful response from AI chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI's response to the user
                  conversation_id:
                    type: string
                    format: uuid
                    description: The conversation ID for maintaining context
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        function:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the function to call
                            arguments:
                              type: string
                              description: JSON string of function arguments
                        id:
                          type: string
                          description: Unique ID for the tool call
                      required:
                        - function
                        - id
                  requires_action:
                    type: boolean
                    description: Whether the response requires additional action
        '400':
          description: Bad request - invalid input
        '401':
          description: Unauthorized - invalid auth token
        '403':
          description: Forbidden - user doesn't have permission to access this resource
        '500':
          description: Internal server error

  /api/{user_id}/conversations:
    get:
      summary: Get user's conversations
      description: Retrieve a list of user's recent conversations
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Better Auth token
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    last_message:
                      type: string
                    message_count:
                      type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get conversation history
      description: Retrieve the full history of a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the conversation
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Better Auth token
      responses:
        '200':
          description: Conversation history
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        role:
                          type: string
                          enum: [user, assistant]
                        content:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Conversation not found